export const USER_ID="USER_ID"
export const ADD_NOTE_TO_AXIOS="ADD_NOTE_TO_AXIOS"
export const USER_KEY="USER_KEY"
export const PLANS_ARRAY="PLANS_ARRAY"
export const SERVER_PLANS_ARRAY="SERVER_PLANS_ARRAY"
export const CLEAR_AXIOS_CONTEXT='CLEAR_AXIOS_CONTEXT'